### ISSUE TITLE
Confuzzius can't connect to local Ganache

### ISSUE THREAD

**Issue by zoltanvilaghy** [christoftorres/ConFuzzius#1]
I tried to use remote fuzzing, and for that I set up a Ganache session on my computer. I have used Ganache previously, and it worked correctly with the tool called Vertigo, with Truffle, and with Geth. When I tried running the tool with the parameters I got the following error:

```
Traceback (most recent call last):
  File "fuzzer/main.py", line 376, in <module>
    main()
  File "fuzzer/main.py", line 204, in main
    instrumented_evm.set_vm_by_name(settings.EVM_VERSION)
  File "/home/zoltan_vilaghy/solidity/ConFuzzius/ConFuzzius/fuzzer/evm/__init__.py", line 227, in set_vm_by_name
    self.set_vm(BYZANTIUM_MAINNET_BLOCK)
  File "/home/zoltan_vilaghy/solidity/ConFuzzius/ConFuzzius/fuzzer/evm/__init__.py", line 96, in set_vm
    block_header = BlockHeader(difficulty=_block.difficulty,
AttributeError: 'NoneType' object has no attribute 'difficulty'

```

**Comment by christoftorres** [comment]
Hi @zoltanvilaghy, thanks for using our tool! We never tried using Ganache for remote fuzzing, we always directly connected to an Ethereum client such as geth. Can you provide us with more background information such that we can reproduce the crash on our side?

**Comment by zoltanvilaghy** [comment]
Hey, thanks for the tool and taking the time to reply :)

The following steps are needed to reproduce the issue:

1. Download Ganache, and start running a local server.
2. In the solidity project, in the truffle-config.js add the needed information to connect to the Ganache server, so something like:
```
networks: {
     development: {
      host: "127.0.0.1",     
      port: 7545,            
      network_id: "5777",      
     },
  },
```
These are default values I think, but you can check it in the Ganache client.
3. Call the ConFuzzius tool with the remote fuzzing parameters like the one given in the readme, so:
```
python3 fuzzer/main.py -a examples/RemiCoin/abi.json -c 0x7dc4f41294697a7903c4027f6ac528c5d14cd7eb -b 5752250 --evm byzantium -g 20 --rpc-host <RPC-HOST> --rpc-port <RPC-PORT>
```
Where <RPC-HOST> is 127.0.0.1, and <RPC-PORT> is 7545 (the ones given in the truffle-config.js file).
4. This should produce the following error:
```
2021-07-16 14:11:31,035 - Main     - INFO - Initializing seed to 0.14240536959060413
Traceback (most recent call last):
  File "fuzzer/main.py", line 372, in <module>
    main()
  File "fuzzer/main.py", line 200, in main
    instrumented_evm.set_vm_by_name(settings.EVM_VERSION)
  File "/home/zoltan_vilaghy/solidity/ConFuzzius/fuzzer/evm/__init__.py", line 227, in set_vm_by_name
    self.set_vm(BYZANTIUM_MAINNET_BLOCK)
  File "/home/zoltan_vilaghy/solidity/ConFuzzius/fuzzer/evm/__init__.py", line 96, in set_vm
    block_header = BlockHeader(difficulty=_block.difficulty,
AttributeError: 'NoneType' object has no attribute 'difficulty'
```

**Comment by christoftorres** [comment]
Hi @zoltanvilaghy :) Thanks for the background information. We had a look and were able to reproduce and debug the error. We think we fixed the bug in our latest commit. Please check it out and let me know if you still have the issue.
