### ISSUE TITLE
How can I open the file with "block" as the file extension?

### ISSUE THREAD

**Issue by Carrot-MoonLion** [christoftorres/ConFuzzius#2]
hi，I am a beginner in smart contract security detection.I am studying your paper and the source code of your tool recently.Can you tell me how can I open the file with "block" as the file extension in the source code of your tool?For example,the file in directory "https://github.com/christoftorres/ConFuzzius/blob/master/fuzzer/evm/4370000.block".I have used a lot of tools to open it and it was garbled.Thank you very  much.

**Comment by christoftorres** [comment]
Hi @Carrot-MoonLion, those block files are "block" objects obtained by calling web3.eth.getBlock(). They have been encoded/stored using Python's pickle library. Hope that helps!
